[package]
name = "biorust-py"
version = "0.0.1"
edition = "2021"

[lib]
name = "biorust_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
biorust-core = { path = "../biorust-core" }